// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCard: typeof import('@nutui/nutui')['Card']
    NutCol: typeof import('@nutui/nutui')['Col']
    NutDivider: typeof import('@nutui/nutui')['Divider']
    NutInput: typeof import('@nutui/nutui')['Input']
    NutRow: typeof import('@nutui/nutui')['Row']
    NutTabPane: typeof import('@nutui/nutui')['TabPane']
    NutTabs: typeof import('@nutui/nutui')['Tabs']
  }
}
